[phases.setup]
nixPkgs = ["python39", "libGL", "ffmpeg", "gcc"]

[phases.install]
cmds = ["python -m venv venv", ". venv/bin/activate", "pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = ". venv/bin/activate && gunicorn app:server"

